-- ==========================================
-- LUXE E-Commerce Database Schema
-- ==========================================

-- 1. Create profiles table
create table public.profiles (
  id uuid not null references auth.users on delete cascade,
  full_name text,
  email text,
  avatar_url text,
  updated_at timestamp with time zone,
  primary key (id)
);

-- RLS: Profiles
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- 2. Trigger for new profiles
-- Automatically triggered when a new user signs up via auth.users
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email, avatar_url)
  values (
    new.id,
    new.raw_user_meta_data ->> 'full_name',
    new.email,
    new.raw_user_meta_data ->> 'avatar_url'
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 3. Create products table (Catalog)
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric not null,
  image_url text,
  category text,
  stock int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS: Products
-- Allow Read for everyone (anon/authenticated).
-- Allow Insert/Update/Delete only for service_role (implicit bypass) or admins (if role system added later).
-- By default, if no policy allows INSERT/UPDATE, only service_role works.
alter table public.products enable row level security;

create policy "Products are viewable by everyone."
  on products for select
  using ( true );

-- 4. Create cart_items table
create table public.cart_items (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  product_id bigint references products not null,
  quantity int default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS: Cart Items
-- Users can only view and edit their own rows.
alter table public.cart_items enable row level security;

create policy "Users can view their own cart items."
  on cart_items for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own cart items."
  on cart_items for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own cart items."
  on cart_items for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own cart items."
  on cart_items for delete
  using ( auth.uid() = user_id );
